export * from "./activeView";
export * from "./courseEditView";
export * from "./courseInputView";
export * from "./courseView";
export * from "./editView";
export * from "./historyView";
export * from "./inputView";
export * from "./mainView";
export * from "./sideView";